antify/codex:
  - source: .editorconfig
    dest: playground/.editorconfig
  - source: eslint.config.js
    dest: playground/eslint.config.js
  - source: .github/workflows/sync-codex-files.yml
    dest: playground/.github/workflows/sync-codex-files.yml
